import './globals.css'

import Menu from '@/Components/header'


export const metadata = {
  title: 'Dennis Snellenberg',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Menu />
        {children}
      </body>
    </html>
  )
}
